version: "3.4"

services:
  database:
    container_name: project112_database
    image: postgres:14.5
    restart: always
    ports:
      - 5532:5432
    networks:
      - project112_net
    volumes:
      - project112_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project112
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  service-api:
    container_name: project112_service-api
    image: jeanbarcellos/project112_service-api:latest
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - project112_net
    environment:
      - PORT=8080
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=project112
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - project112_service-api_data:/logs

networks:
  project112_net:
    name: project112_net
    driver: bridge

volumes:
  project112_database_data:
    name: project112_database_data
    driver: local

  project112_service-api_data:
    name: project112_service-api_data
    driver: local