server:
  port: ${PORT:8082}

spring:
  application:
    name: project112-service-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5532}/${DB_NAME:project112}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: none # create
              create-target: create-schema.sql
              create-source: metadata

  flyway:
    enabled: true
    default-schema: project112

  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger
    operationsSorter: alpha
    tagsSorter: alpha