server:
  port: ${PORT:8080}

spring:
  application:
    name: project112-service-api

  data:
    mongodb:
      uri: mongodb://localhost:27017/project112

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger
    operationsSorter: alpha
    tagsSorter: alpha